version: 2.1

orbs:
  python: circleci/python@0.2.1
  slack: circleci/slack@4.0.3

jobs:
  announce-build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Starting build #<< pipeline.number >> on ${CIRCLE_BRANCH} in ${CIRCLE_PROJECT_REPONAME}"
                  }
                }
              ]
            }
          event: always
          channel: dev
  check-formatting:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          command: |
            pycodestyle --count --config ./.pycodestyles --exclude ./venv,./testData.py ./
          name: Format Check
  dependency-audit:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          command: |
            safety check
          name: Audit
  test:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          command: python tests.py
          name: Test
  notify-end-of-pipeline:
    docker:
      - image: "cimg/base:stable"
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Build #<< pipeline.number >> on ${CIRCLE_BRANCH} in ${CIRCLE_PROJECT_REPONAME}"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Create PR"
                      },
                      "url": "<< pipeline.project.git_url >>"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Build"
                      },
                      "url": "https://app.circleci.com/pipelines/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
                    }
                  ]
                }
              ]
            }
          event: pass
          channel: dev

workflows:
  main:
    jobs:
      - announce-build:
          context: Slack
      - test:
          requires:
            - announce-build
      - check-formatting:
          requires:
            - announce-build
      - dependency-audit:
          requires:
            - announce-build
      - notify-end-of-pipeline:
          requires:
            - test
            - check-formatting
            - dependency-audit
          context: Slack
